version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    container_name: elasticsearch
    environment:
      - "network.host=0.0.0.0"
      - "discovery.zen.minimum_master_nodes=1"
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms8g -Xmx12g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./data/es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.1
    ports:
      - "5601:5601"
    networks:
      - esnet
    environment:
      - "server.port=5601"
      - "server.host=0.0.0.0"
      - "elasticsearch.url=http://elasticsearch:9200"
      - "xpack.security.enabled=false"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.1
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch.example.org

  rabbitmq:
    build: rabbitmq/
    ports:
      - "5672:5672"
      - "1883:1883"
      - "9001:9001"
      - "15672:15672"
    networks:
      - esnet

  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - rabbitmq

volumes:
  es-data:
    driver: local

networks:
  esnet:
    driver: bridge
