version: '3'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx12g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - stack
    volumes:
      - ./data/es-data:/usr/share/elasticsearch/data

  rabbitmq:
    build: rabbitmq/
    ports:
      - "5672:5672"
      - "1883:1883"
      - "9001:9001"
      - "15672:15672"
    networks:
      - stack

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - stack
    depends_on:
      - elasticsearch

  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - stack
    depends_on:
      - elasticsearch
      - rabbitmq

volumes:
  es-data:
    driver: local

networks:
  stack:
    driver: bridge
